#!/bin/sh
# This is the /etc/init.d file for puppetd
# Modified for CSW
#
# description: puppetd - Puppet Automation Client
#

. /lib/svc/share/smf_include.sh

prefix=/opt/local
exec_prefix=${prefix}/bin

pidfile=/var/lib/puppet/run/agent.pid

case "$1" in
start)
    cd /
    # Start daemons.

    printf "Starting Puppet client services:"

    ${exec_prefix}/puppet agent --daemonize

    printf " puppet agent"
    echo ""
    ;;
stop)
    printf "Stopping Puppet client services:"
    kill `cat $pidfile`

    printf " puppet agent"
    echo ""
    ;;
restart)
    printf "Restarting Puppet client services:"
    kill -HUP `cat $pidfile`

    printf " puppet agent"
    echo ""
    ;;
reload)
    printf "Reloading Puppet client services:"

    kill -HUP `cat $pidfile`

    printf " puppet agent"
    echo ""
    ;;
status)
    if [ -f $pidfile ]; then
        pid=`cat $pidfile`
        curpid=`pgrep puppet`
				curpid=`pgrep -f "ruby.*puppet\ agent"`
        if [ "$pid" -eq "$curpid" ]; then
            exit 0
        else
            exit 1
        fi
    else
        exit 1
    fi
esac
exit 0
