#!/bin/bash
#

. /lib/svc/share/smf_include.sh
. /etc/profile

prefix=/opt/local
exec_prefix=${prefix}/bin
fullcat=/opt/local/bin/cat

pidfile=/var/lib/puppet/run/master.pid

case "$1" in
start)
    cd /
    # Start daemons.

    printf "Starting Puppet server services:"

    ${exec_prefix}/puppet master --daemonize 

    printf " puppet master"
    echo ""
    ;;
stop)
    printf "Stopping Puppet server services:"
    kill `$fullcat $pidfile`

    printf " puppetmasterd"
    echo ""
    ;;
restart)
    printf "Restarting Puppet server services:"
    kill -HUP `$fullcat $pidfile`

    printf " puppetmasterd"
    echo ""
    ;;
reload)
    printf "Reloading Puppet server services:"

    kill -HUP `$fullcat $pidfile`

    printf " puppetmasterd"
    echo ""
    ;;
status)
    if [ -f $pidfile ]; then
        pid=`$fullcat $pidfile`
        curpid=`pgrep -f "ruby.*puppet\ master"`
        if [ "$pid" -eq "$curpid" ]; then
            exit 0
        else
            exit 1
        fi
    else
        exit 1
    fi
esac
exit 0
